repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: ^tests/
  - id: check-toml
  - id: debug-statements
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
  hooks:
  - id: pretty-format-yaml
    exclude: ^tests/
    args: [--preserve-quotes, --autofix, --indent, '2']
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore
  - id: python-no-log-warn
  - id: python-use-type-annotations
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    args: [--safe, --quiet, --line-length=100]
- repo: https://github.com/humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
  - id: autoflake
    args: [--in-place, --remove-unused-variable]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/asottile/pyupgrade
  rev: v3.4.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: [--max-line-length=100]
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.2.0
  hooks:
  - id: setup-cfg-fmt
- repo: https://github.com/tdegeus/conda_envfile
  rev: v0.4.2
  hooks:
  - id: conda_envfile_parse
    files: environment.yaml
